import { z } from 'zod';

export const orgSettingsUpdateSchema = z.object({
  orgId: z.string().uuid(),
  companyName: z.string().trim().min(1).max(200).nullable().optional(),
  companyLogoPath: z.string().trim().min(1).max(500).nullable().optional(),
  timezone: z.string().trim().min(1).max(100).nullable().optional(),
  businessType: z.string().trim().min(1).max(200).nullable().optional(),
  officeType: z.string().trim().min(1).max(120).nullable().optional(),
  reportCadence: z.enum(['weekly', 'fortnightly']).nullable().optional(),
  serviceAreaSuburbs: z.array(z.string().trim().min(1).max(120)).max(200).optional(),
  buyerIntakePublicEnabled: z.boolean().optional(),
  buyerIntakeManualEnabled: z.boolean().optional(),
  listingStatusOptions: z.array(z.string().trim().min(1).max(120)).max(200).optional(),
  defaultWorkdayStartMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  defaultWorkdayEndMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  defaultDailyCapacityMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  defaultJobDurationMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  defaultTravelBufferMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  travelBufferEnabled: z.boolean().optional(),
  announcementsEnabled: z.boolean().optional(),
  urgentAnnouncementBehavior: z.enum(['modal', 'banner']).optional(),
  commFromName: z.string().trim().min(1).max(200).nullable().optional(),
  commFromEmail: z.string().trim().email().max(320).nullable().optional(),
  commReplyToEmail: z.string().trim().email().max(320).nullable().optional(),
  automationsDisabled: z.boolean().optional(),
  xeroSyncPaymentsEnabled: z.boolean().optional(),
  xeroSalesAccountCode: z.string().trim().max(50).nullable().optional(),
  xeroTaxType: z.string().trim().max(50).nullable().optional(),
  marginWarningPercent: z.number().min(0).max(100).nullable().optional(),
  marginCriticalPercent: z.number().min(0).max(100).nullable().optional(),
  varianceThresholdPercent: z.number().min(0).max(100).nullable().optional(),
  lateRiskMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  idleThresholdMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  staleLocationMinutes: z.number().int().min(0).max(24 * 60).nullable().optional(),
  riskRadiusKm: z.number().min(0).max(1000).nullable().optional(),
  qualityCallbackDays: z.number().int().min(1).max(365).optional(),
  hqAddressLine1: z.string().trim().min(1).max(200).nullable().optional(),
  hqAddressLine2: z.string().trim().max(200).nullable().optional(),
  hqSuburb: z.string().trim().max(120).nullable().optional(),
  hqState: z.string().trim().max(120).nullable().optional(),
  hqPostcode: z.string().trim().max(20).nullable().optional(),
});

export type OrgSettingsUpdateInput = z.infer<typeof orgSettingsUpdateSchema>;
