export const AUTOMATIONS_ENABLED = process.env.AUTOMATIONS_ENABLED !== 'false';

const DEFAULT_MAX_ACTIONS_PER_MINUTE = 250;
const DEFAULT_MAX_LINEAGE_DEPTH = 3;

export const AUTOMATIONS_MAX_ACTIONS_PER_MINUTE = Number(
  process.env.AUTOMATIONS_MAX_ACTIONS_PER_MINUTE ?? DEFAULT_MAX_ACTIONS_PER_MINUTE
);

export const AUTOMATIONS_MAX_LINEAGE_DEPTH = Number(
  process.env.AUTOMATIONS_MAX_LINEAGE_DEPTH ?? DEFAULT_MAX_LINEAGE_DEPTH
);

export const AUTOMATIONS_DISPATCH_BATCH = Number(process.env.AUTOMATIONS_DISPATCH_BATCH ?? 50);
